name: actions

on:
  push:
    branches:
      - '**'

jobs:
  check-eslint:
    name: Check the code by eslin
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: run Esinter
      - run: make lint
